### ISSUE TITLE
关于Attention Module输出的激活函数

### ISSUE THREAD

**Issue by zasr99** [Shuaizhang7/AttentionGAN-for-Cloud-removal#6]
您好，请问在您提供的代码中，计算云注意力图（Attention Module）的UnetGenerator方法的输出层的激活函数使用的是Tanh（），将输出映射到[-1,1]中，但是您在论文中写到云注意力图的范围为[0,1]，请问是还有对云注意力图有额外的操作将其映射至[0,1]吗？
![屏幕截图 2024-10-11 230256](https://github.com/user-attachments/assets/761d2119-6f85-447c-a675-de125ef81a3f)

**Comment by Shuaizhang7** [comment]
您好，具体的细节我记不太清楚了，您可以把https://github.com/Shuaizhang7/AttentionGAN-for-Cloud-removal/blob/da047b3992c8a027a0a561b4b9874e85e9da5db7/models/pix2pix_attn_model.py#L96 这一行里的Mask打印一下看看值大概的范围是否是[0,1]。如果不是的话，可以加一个其他的函数再映射到0到1吧

**Comment by zasr99** [comment]
> 您好，具体的细节我记不太清楚了，您可以把
> 
> https://github.com/Shuaizhang7/AttentionGAN-for-Cloud-removal/blob/da047b3992c8a027a0a561b4b9874e85e9da5db7/models/pix2pix_attn_model.py#L96
> 
> 这一行里的Mask打印一下看看值大概的范围是否是[0,1]。如果不是的话，可以加一个其他的函数再映射到0到1吧

好的，十分感谢
